// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQ9isjjMG1_V__NklQ1afDXakU3WweH0',
    appId: '1:152666881394:web:f05fe186f26d87d961b1eb',
    messagingSenderId: '152666881394',
    projectId: 'pg-laundry',
    authDomain: 'pg-laundry.firebaseapp.com',
    storageBucket: 'pg-laundry.firebasestorage.app',
    measurementId: 'G-9F6G4RQZGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbIIYq6rw1HSxJDwxo8xJMmAmalS1_xc',
    appId: '1:152666881394:android:05820cdd89bc099c61b1eb',
    messagingSenderId: '152666881394',
    projectId: 'pg-laundry',
    storageBucket: 'pg-laundry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEIoBI65BDp-NFMSsXCAQNqHODymqPK68',
    appId: '1:152666881394:ios:3b04d68a2eaffb7961b1eb',
    messagingSenderId: '152666881394',
    projectId: 'pg-laundry',
    storageBucket: 'pg-laundry.firebasestorage.app',
    iosBundleId: 'com.example.laundryBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEIoBI65BDp-NFMSsXCAQNqHODymqPK68',
    appId: '1:152666881394:ios:3b04d68a2eaffb7961b1eb',
    messagingSenderId: '152666881394',
    projectId: 'pg-laundry',
    storageBucket: 'pg-laundry.firebasestorage.app',
    iosBundleId: 'com.example.laundryBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfQ9isjjMG1_V__NklQ1afDXakU3WweH0',
    appId: '1:152666881394:web:7c9baec2b57ccd0961b1eb',
    messagingSenderId: '152666881394',
    projectId: 'pg-laundry',
    authDomain: 'pg-laundry.firebaseapp.com',
    storageBucket: 'pg-laundry.firebasestorage.app',
    measurementId: 'G-RH0DJG9S0T',
  );
}
